version: "3.8"

services:
  app:
    build: .
    container_name: coder_edu_backend
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=******
      - DATABASE_NAME=coder_edu_backend
      - JWT_SECRET=******
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=******
    volumes:
      - ./uploads:/app/uploads
    networks:
      - coder_edu_network

  db:
    image: mysql:8.0
    container_name: coder_edu_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=******
      - MYSQL_DATABASE=coder_edu_backend
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
    networks:
      - coder_edu_network

  redis:
    image: redis:7.0
    container_name: coder_edu_redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass ******
    volumes:
      - redis_data:/data
    networks:
      - coder_edu_network

networks:
  coder_edu_network:
    driver: bridge

volumes:
  mysql_data:
  mysql_config:
  redis_data: