server:
  port: 8080
  mode: "debug"

database:
  host: "localhost"
  port: 3306
  user: "root"
  password: "REDACTED_PASSWORD"
  dbname: "coder_edu_backend"
  charset: "utf8mb4"
  parseTime: true

jwt:
  secret: "REDACTED_JWT_SECRET"
  expire_hours: 12

storage:
  type: "local" # or "minio"
  local_path: "./uploads"
  minio_endpoint: "localhost:9000"
  minio_access_key: "minioadmin"
  minio_secret_key: "minioadmin"
  minio_bucket: "coder_edu_backend"

Tracing:
  Enabled: false
  CollectorEndpoint: http://localhost:8080/api/traces

judge0:
  api_key: "REDACTED_JUDGE0_KEY"
  url: "https://judge0-ce.p.rapidapi.com/submissions?wait=true&base64_encoded=true"
  host: "judge0-ce.p.rapidapi.com"