server:
  port: 8080
  mode: "debug"

database:
  host: "localhost"
  port: 3306
  user: "root"
  password: "******"
  dbname: "coder_edu_backend"
  charset: "utf8mb4"
  parseTime: true

jwt:
  secret: "******"
  expire_hours: 12

storage:
  type: "oss" # "local" or "minio" or "oss"
  local_path: "./uploads"
  minio_endpoint: "localhost:9000"
  minio_access_key: "******"
  minio_secret_key: "******"
  minio_bucket: "coder_edu_backend"
  oss_endpoint: "oss-ap-southeast-1.aliyuncs.com"
  oss_access_key: "******"
  oss_secret_key: "******"
  oss_bucket: "coder-edu-backend"

tracing:
  enabled: false
  collector_endpoint: http://localhost:8080/api/traces

judge0:
  api_key: "******"
  url: "https://judge0-ce.p.rapidapi.com/submissions?wait=true&base64_encoded=true"
  host: "judge0-ce.p.rapidapi.com"

cors:
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:5173"
    - "http://127.0.0.1:3000"
    - "http://127.0.0.1:5173"

rate_limit:
  max_requests: 200
  window_minutes: 1

redis:
  host: "localhost"
  port: 6379
  password: "******"
  db: 0

ai:
  base_url: "https://api.deepseek.com"
  api_key: "******"
  model: "deepseek-chat"